name: Create PR from main to develop

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Create Pull Request from main to develop
        uses: peter-evans/create-pull-request@v7
        with:
          source: main
          destination: develop
          title: 'Sync main into develop'
          body: 'Automated PR to sync main into develop'
          draft: false